### ISSUE TITLE
Angular中不能滚动

### ISSUE THREAD

**Issue by wenxiayili** [ansenhuang/axe#2]
问题描述：在angular（6.1）中，我模拟了一段数据
typescript:
`
export class AppComponent implements OnInit {
  title = 'scrollText';
  data1: any[] = [];
  ngOnInit(): void {
    this.text();
    setTimeout(() => {
      for (let i = 0; i < 30; i ++) {
        this.data1.push({
          id: i
        });
      }
    }, 1000);
  }
  text() {
    const rootEl = document.getElementById('root');

    rootEl.style.height = '100vh';
    rootEl.style.overflow = 'hidden';

    const scroller = new Scroller(rootEl, {});
    scroller.enable();

    scroller.on('scrollstart', info => {
      // tslint:disable-next-line:no-console
      // console.info('scrollstart', info);
    });

    scroller.on('scroll', info => {
      // tslint:disable-next-line:no-console
      // console.info('scroll', info);
    });

    scroller.on('scrollend', info => {
      // tslint:disable-next-line:no-console
      // console.info('scrollend', info);
    });
  }
}
`
@ansenhuang 
页面延迟一秒中 加载数据。此时，页面是不能滚动的，就像卡住了一般，不能动。作者能解释下不？<div id="root">
  <div class="scroller">
    <div>
      <p *ngFor="let item of data1;let i = index;" >{{i}}</p>
    </div>
    <div>
        <p *ngFor="let item of data1;let i = index;" >{{i}}</p>
    </div>
  </div>
</div>

**Comment by ansenhuang** [comment]
你初始化的时候，数据还没加载完，此时页面的高度是0，因此不能滚动；数据加载完成后，你需要更新一下scroller，让其重新计算滚动高度。

**Comment by wenxiayili** [comment]
@ansenhuang 相关的API？

**Comment by wenxiayili** [comment]
> 你初始化的时候，数据还没加载完，此时页面的高度是0，因此不能滚动；数据加载完成后，你需要更新一下scroller，让其重新计算滚动高度。

相关API?

**Comment by ansenhuang** [comment]
> > 你初始化的时候，数据还没加载完，此时页面的高度是0，因此不能滚动；数据加载完成后，你需要更新一下scroller，让其重新计算滚动高度。
> 
> 相关API?

scroller.refresh()，文档中有详细说明，你可以先看看

**Comment by wenxiayili** [comment]
> > > 你初始化的时候，数据还没加载完，此时页面的高度是0，因此不能滚动；数据加载完成后，你需要更新一下scroller，让其重新计算滚动高度。
> > 
> > 
> > 相关API?
> 
> scroller.refresh()，文档中有详细说明，你可以先看看

好的谢谢
